name: Generate Pac-Man

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hanumanraj07
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Generate Pac-Man SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hanumanraj07
          outputs: |
            dist/pacman-contribution-graph.svg?color_snake=#00ff41&color_dots=#0d1117,#003b00,#006400,#00a000,#00cc00
            dist/pacman-contribution-graph-dark.svg?color_snake=#00ff41&color_dots=#0d1117,#003b00,#006400,#00a000,#00cc00&palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
